### ISSUE TITLE
Akalath Quarantine (3023.js) in/out mech doesn't appear to work

### ISSUE THREAD

**Issue by Shiriko-star** [Multarix/tera-guide-revised#1]
TTS not working and no visible message on screen.

Everything else in this dungeon functions normally.

**Comment by Multarix** [comment]
This issue is fixed, however I did notice when doing a run to verify I've fixed it, that quite a few of the telegraphs were incorrect, so I'll keep this open until I fix that

**Comment by Multarix** [comment]
Okay, I worked out the issue with telegraphs. It was caused by an issue in my conversion script. I'll roll out fixes for guides in a bit. Thanks for reporting!
