### ISSUE TITLE
CSN/BAHAAR

### ISSUE THREAD

**Issue by owu-master** [Multarix/tera-guide-revised#7]
Hi, OUT/IN mech is not working in CSN/CSH. 
Bahaar doesn't has indicators on waves, don't really need them but would be a nice addition. 
Attached the .txt with all the errors i got thruout the day.

[GUIDE ERROR.txt](https://github.com/Multarix/tera-guide-revised/files/5549238/GUIDE.ERROR.txt)

**Comment by Multarix** [comment]
I will take a look at this after I complete assassins creed Valhalla... Which might take awhile.

However it's cs/ bahaar, 2 dungeons I don't do very often. Until then I'd suggest disabling those guides

**Comment by Multarix** [comment]
@owu-master hey there, I just pushed an update that should fix the errors mentioned in the file you uploaded. Feel free to test it and see if they fixed the issues :)

**Comment by Multarix** [comment]
seeing as there is not response I'm going to assume the issue is fixed
